In [29]:
import pandas as pd

In [30]:
df = pd.read_csv("../data/cleaned_base.csv")
df.head()

,nct_id,study_title,study_status,conditions,interventions,sponsor,phases,Locations,start_date,completion_date
0,NCT07048990,Feasibility of Empowerment Group Therapy on Uk...,RECRUITING,Depression NOS,BEHAVIORAL: Empowerment Group Therapy,"Charite University, Berlin, Germany",NaN,"National Medical University Bogomolets, Kyiv, ...",2024-11-05,2025-09
1,NCT02958527,Drug Use Investigation Of Effexor (SECONDARY D...,COMPLETED,Depression/Depressed State,DRUG: venlafaxine,Pfizer's Upjohn has merged with Mylan to form ...,NaN,NaN,2016-10-03,2020-05-11
2,NCT03278938,"Add-on to Cognitive, Event-Related Potentials ...",WITHDRAWN,Depressive Illness,DRUG: bupropion|DRUG: citalopram,New York State Psychiatric Institute,PHASE4,"New York State Psychiatric Institute, New York...",2012-06-29,2016-01
3,NCT07528014,ATLAS-1: Advanced Trial for Longitudinal Asses...,RECRUITING,Depressed Mood,NaN,"Salma Health, Inc.",NaN,"Salma Health, La Jolla, California, 92037, Uni...",2026-03-25,2037-03
4,NCT03966833,Using Group Interpersonal Psychotherapy to Imp...,COMPLETED,Mental Depression,BEHAVIORAL: IPT-G|BEHAVIORAL: Unconditional Ca...,George Washington University,NaN,"BRAC Uganda, Kampala, Uganda",2019-05-26,2022-09-30

In [31]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 10 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   nct_id           1000 non-null   object
 1   study_title      1000 non-null   object
 2   study_status     1000 non-null   object
 3   conditions       1000 non-null   object
 4   interventions    936 non-null    object
 5   sponsor          1000 non-null   object
 6   phases           271 non-null    object
 7   Locations        925 non-null    object
 8   start_date       992 non-null    object
 9   completion_date  969 non-null    object
dtypes: object(10)
memory usage: 78.2+ KB

In [32]:
df["nct_id"].duplicated().sum()

np.int64(0)

In [33]:
df_clean = df.drop_duplicates(subset=["nct_id"]).copy()

print("Before:", df.shape)
print("After:", df_clean.shape)

Before: (1000, 10)
After: (1000, 10)

In [34]:
df_clean.isnull().sum()

nct_id               0
study_title          0
study_status         0
conditions           0
interventions       64
sponsor              0
phases             729
Locations           75
start_date           8
completion_date     31
dtype: int64

In [35]:
# phases - > 729 너무 많음

In [36]:
df_clean["start_date"] = pd.to_datetime(df_clean["start_date"], errors="coerce")
df_clean["completion_date"] = pd.to_datetime(df_clean["completion_date"], errors="coerce")

df_clean[["start_date", "completion_date"]].head()

  start_date completion_date
0 2024-11-05      2025-09-01
1 2016-10-03             NaT
2 2012-06-29      2016-01-01
3 2026-03-25      2037-03-01
4 2019-05-26             NaT

In [37]:
df_clean["start_date"] = pd.to_datetime(df_clean["start_date"],errors="coerce")
df_clean["completion_date"] = pd.to_datetime(df_clean["completion_date"],errors="coerce")

df_clean[["start_date","completion_date"]].head()

  start_date completion_date
0 2024-11-05      2025-09-01
1 2016-10-03             NaT
2 2012-06-29      2016-01-01
3 2026-03-25      2037-03-01
4 2019-05-26             NaT

In [45]:
object_cols = df_clean.select_dtypes(include ="object").columns
df_clean[object_cols] = df_clean[object_cols].apply(lambda col: col.str.strip())
df_clean[object_cols] = df_clean[object_cols].replace("", pd.NA)

for col in object_cols:
    print(f"\n===== {col} =====")
    print(df_clean[col].value_counts(dropna=False).head(10))

===== nct_id =====
nct_id
NCT00076622    1
NCT07048990    1
NCT02958527    1
NCT03278938    1
NCT07528014    1
NCT03966833    1
NCT05797428    1
NCT05306093    1
NCT06337773    1
NCT01255072    1
Name: count, dtype: int64

===== study_title =====
study_title
Electrical Stimulation in Patients With Unipolar Major Depression                                                                                           2
Active Elements of Digital Single-session Interventions                                                                                                     1
Developing the Precision Nursing Education Program to Young Colorectal Cancer Survivors                                                                     1
Sensitivity to Ovarian Hormones and Depression in Adolescents                                                                                               1
Medication Treatment for Depression in Nursing Home Residents                                                                                               1
Feasibility of Empowerment Group Therapy on Ukrainian Adult Outpatients                                                                                     1
Drug Use Investigation Of Effexor (SECONDARY DATA COLLECTION STUDY; SAFETY AND EFFICACY OF EFFEXOR.UNDER JAPANESE MEDICAL PRACTICE)                         1
Depressed Mood and Anhedonia in Healthy Adults                                                                                                              1
Utilizing Embodied Artificial Intelligence (AI) for the Development of Digital Cognitive Behavioral Therapy (CBT) for Depression in Virtual Reality (VR)    1
Effect of a Nutritional Supplement on Mental Wellness in Adults                                                                                             1
Name: count, dtype: int64

===== study_status =====
study_status
COMPLETED                  605
UNKNOWN                    151
RECRUITING                  94
TERMINATED                  53
NOT_YET_RECRUITING          35
WITHDRAWN                   28
ACTIVE_NOT_RECRUITING       24
SUSPENDED                    5
ENROLLING_BY_INVITATION      5
Name: count, dtype: int64

===== conditions =====
conditions
Depression                                   808
Major Depressive Disorders                    10
Depressive Disorders                           5
Depression|Treatment Resistant Depression      4
Anxiety Disorders|Depressive Disorders         3
Postpartum Depression|Depression               3
Depressive Disorder                            3
Depression|Depression, Postpartum              3
Major Depressive Disorder                      3
Depression, Postpartum|Depression              3
Name: count, dtype: int64

===== interventions =====
interventions
NaN                                           64
DRUG: Escitalopram                             4
DRUG: Sertraline                               4
BEHAVIORAL: Cognitive Behavioral Therapy       4
DEVICE: Transcranial Magnetic Stimulation      3
BEHAVIORAL: Lifestyle Medicine                 3
PROCEDURE: Acupuncture                         3
DRUG: duloxetine                               3
BEHAVIORAL: Deprexis|BEHAVIORAL: Wait-list     2
DRUG: Effexor XR                               2
Name: count, dtype: int64

===== sponsor =====
sponsor
Massachusetts General Hospital                 29
University of Pittsburgh                       18
National Institute of Mental Health (NIMH)     16
Weill Medical College of Cornell University    16
Stanford University                            15
University of California, Los Angeles          14
Northwestern University                        12
University of California, San Francisco        12
Chinese University of Hong Kong                12
New York State Psychiatric Institute           11
Name: count, dtype: int64

===== phases =====
phases
NaN              729
PHASE4            88
PHASE2            68
PHASE3            40
PHASE1            29
PHASE2|PHASE3     18
EARLY_PHASE1      16
PHASE1|PHASE2     12
Name: count, dtype: int64

===== Locations =====
Locations
NaN                                                                                                             75
Massachusetts General Hospital, Boston, Massachusetts, 02114, United States                                      9
Northwestern University, Chicago, Illinois, 60611, United States                                                 6
Butler Hospital, Providence, Rhode Island, 02906, United States                                                  6
National Institutes of Health Clinical Center, 9000 Rockville Pike, Bethesda, Maryland, 20892, United States     5
University of Michigan, Ann Arbor, Michigan, 48109, United States                                                5
The Chinese University of Hong Kong, Shatin, Hong Kong                                                           5
National Institutes of Health Clinical Center, Bethesda, Maryland, 20892, United States                          4
Icahn School of Medicine at Mount Sinai, New York, New York, 10029, United States                                4
Western Psychiatric Institute and Clinic, Pittsburgh, Pennsylvania, 15213, United States                         4
Name: count, dtype: int64

In [46]:
df_clean.to_csv("../data/cleaned_trials.csv", index=False, encoding="utf-8-sig")