In [1]:
import pandas as pd

In [2]:
import sqlite3

In [3]:
df = pd.read_csv("../data/cleaned_trials.csv")

In [5]:
conn = sqlite3.connect("../data/clinical_trials.db")

In [8]:
df.to_sql(
    "clinical_trials",
    conn,
    if_exists="replace",
    index = False
)

conn.close()

In [9]:
conn = sqlite3.connect("../data/clinical_trials.db")

query = """
SELECT COUNT(*) AS total_rows
FROM clinical_trials;
"""

pd.read_sql_query(query, conn)

   total_rows
0        1000

In [10]:
query = """
PRAGMA table_info(clinical_trials);
"""

pd.read_sql_query(query, conn)

   cid             name  type  notnull dflt_value  pk
0    0           nct_id  TEXT        0       None   0
1    1      study_title  TEXT        0       None   0
2    2     study_status  TEXT        0       None   0
3    3       conditions  TEXT        0       None   0
4    4    interventions  TEXT        0       None   0
5    5          sponsor  TEXT        0       None   0
6    6           phases  TEXT        0       None   0
7    7        Locations  TEXT        0       None   0
8    8       start_date  TEXT        0       None   0
9    9  completion_date  TEXT        0       None   0

In [ ]:
conn.close()